# Generated by Django 4.1.7 on 2023-03-17 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auxiliares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Farol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Perfis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Seguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nomecurto', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Seguradora',
                'verbose_name_plural': 'Seguradoras',
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TbaxStatusCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TbaxStatusOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TbaxTipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipocliente', models.CharField(db_column='TipoCliente', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TbaxTipoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TbaxTipoOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TbCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('nome_curto', models.CharField(max_length=40)),
                ('cep', models.CharField(max_length=40)),
                ('bairro', models.CharField(max_length=40)),
                ('cidade', models.CharField(max_length=40)),
                ('logradouro', models.CharField(max_length=100)),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(max_length=18)),
                ('razaosocial', models.CharField(max_length=128)),
                ('fkcontatoprimario', models.CharField(blank=True, max_length=250, null=True)),
                ('fkcontatotecnico', models.CharField(max_length=250)),
                ('clientestatus', models.CharField(choices=[('Desativado ou suspenso', 'Desativado ou suspenso'), ('Implatado(pacote básico - legacy', 'Implatado(pacote básico - legacy'), ('Implatado', 'Implatado'), ('Implatado(pacote individualizado - legacy)', 'Implatado(pacote individualizado - legacy)'), ('Não Implatado', 'Não Implatado'), ('Em Prospeccao', 'Em Prospeccao'), ('Em Homologacao', 'Em Homologacao'), ('Sem servico financeiro atrelado', 'Sem servico financeiro atrelado')], max_length=300)),
                ('data_criacao', models.DateField()),
                ('data_modificação', models.DateField()),
                ('status', models.CharField(choices=[('Desativado ou suspenso', 'Desativado ou suspenso'), ('Implatado(pacote básico - legacy', 'Implatado(pacote básico - legacy'), ('Implatado', 'Implatado'), ('Implatado(pacote individualizado - legacy)', 'Implatado(pacote individualizado - legacy)'), ('Não Implatado', 'Não Implatado'), ('Em Prospeccao', 'Em Prospeccao'), ('Em Homologacao', 'Em Homologacao'), ('Sem servico financeiro atrelado', 'Sem servico financeiro atrelado')], max_length=50)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tbcontato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=20)),
                ('data_criacao', models.DateField()),
                ('data_modificação', models.DateField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criado_por', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificado_por', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=250)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('data_criacao', models.DateField()),
                ('datainicio', models.DateField()),
                ('dataencerramento', models.DateField()),
                ('operacaostatus', models.CharField(choices=[('Em processo de Implantacao', 'Em processo de Implantacao'), ('Implantado', 'Implantado'), ('Não implantado', 'Não implantado'), ('Operação suspensa', 'Operação suspensa'), ('Operação encerrada', 'Operação encerrada'), ('Operação com gestao conjunta', 'Operação com gestao conjunta'), ('Operação em run-off', 'Operação em run-off'), ('Não defenido', 'Não defenido'), ('Dados em homologacao sem auxiliares', 'Dados em homologacao sem auxiliares'), ('Dados em homologacao', 'Dados em homologacao'), ('Operacao sem gestao FFC', 'Operacao sem gestao FFC')], max_length=300)),
                ('fkcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tbcliente')),
                ('fkfarmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tbcontato')),
                ('fkseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.seguradora')),
            ],
            options={
                'verbose_name': 'Operacao',
                'verbose_name_plural': 'Operacoes',
            },
        ),
    ]
