# Generated by Django 4.1.7 on 2023-03-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tbcliente',
            name='cep',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tbcliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tbcliente',
            name='data_criacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tbcliente',
            name='data_modificação',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tbcliente',
            name='fkcontatotecnico',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tbcliente',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tbcliente',
            name='razaosocial',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tbcontato',
            name='data_criacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tbcontato',
            name='data_modificação',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tbcontato',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tbcontato',
            name='nome',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tbcontato',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
