# Generated by Django 4.1.7 on 2023-03-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_tbcliente_bairro_alter_tbcliente_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguradora',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=20),
        ),
    ]
