# Generated by Django 4.1.7 on 2023-03-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_seguradora_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcliente',
            name='tipo',
            field=models.CharField(choices=[('Varejista', 'Varejista'), ('Cooperativa', 'Cooperativa'), ('Financeira', 'Financeira'), ('Outros', 'Outros')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
