# Generated by Django 4.1.7 on 2023-03-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_tbcliente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcliente',
            name='clientestatus',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=300),
        ),
        migrations.AlterField(
            model_name='tbcliente',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=50),
        ),
    ]
