# Generated by Django 4.1.7 on 2023-03-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_tbcliente_clientestatus_alter_tbcliente_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcontato',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
