# Generated by Django 4.1.7 on 2023-03-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_tbcontato_razao_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcliente',
            name='clientestatus',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Implantacao', 'Implantacao')], max_length=300),
        ),
        migrations.AlterField(
            model_name='tbcliente',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Implantacao', 'Implantacao')], max_length=50),
        ),
    ]
