# Generated by Django 4.1.7 on 2023-03-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_tbcliente_clientestatus_alter_tbcliente_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguradora',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Implantacao', 'Implantacao')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tbcontato',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Implantacao', 'Implantacao')], max_length=20),
        ),
    ]
